services:
  - type: web
    name: prograweb2
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: heroku-php-apache2 public/
    postdeployCommand: |
      php artisan key:generate --force
      mkdir -p /tmp/database
      touch /tmp/database/database.sqlite
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:IU8qkIgZ02Ed44SxyitCkUhZ0Wu7z96bA1iCBc4GXCY=
      - key: APP_URL
        value: https://prograweb2.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
